spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
  flyway:
    # オプションなしだとH2 Consoleがバグる
    url: jdbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
    user: sa
    password:
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    root: INFO
    io:
      r2dbc: DEBUG
